version: 2
jobs:
  deploy_job:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: echo "CI start"
      - run: go run cmd/main.go
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_job:
        filters:
          branches:
            only: develop